### PR TITLE
Update index.html.ejs

### PR DESCRIPTION
**Pull request by diomed**
add link to system on index page

### CODE REVIEW

**Comment by diomed** [comment]
why not, tho?

**Comment by sakofchit** [comment]
you put a link rel inside of the window pane in the docs which doesn't display or do anything. wasn't sure what you were trying to do there.

Screenshot 2023-11-26 at 6 16 00 PM

**Comment by diomed** [comment]
but it would display that link.

or you could edit it, put it in code.

as long as it's on main html page somewhere and easily accessible, for copy-pasting into our own project.
- that was my intention

**Comment by sakofchit** [comment]
fair, but why in the window pane? seemed kinda random

also i didn't feel it's really necessary since the link to this repo is linked in the docs which has the link to the npm package.

**Comment by diomed** [comment]
honestly, I just wanted to put it **somewhere** and seemed appropriate to put it where it wouldnt bother you too much, but would still be available. ¯\_(ツ)_/¯

**Comment by sakofchit** [comment]
what I meant was that i feel like it'd probably need it's own section rather than being put randomly in the window pane.

i.e. could have a "Getting Started" section right below the "Intro" in the docs (kinda like how it's formatted in the readme).

> ## Getting Started
> There are a couple of ways you can get started with System.css!
> 
> **Import from CDN (easiest)**
> 
> Add the following to your head tag:
> 
> ```html
> <link rel="stylesheet" href="https://unpkg.com/@sakun/system.css" />
> ```
> 
> or 
> 
> **Import from [npmjs](https://www.npmjs.com/package/@sakun/system.css)**
> 
>     npm i @sakun/system.css

something like that––again, it's a super minor detail but if you'd like to do that, I'd be more than happy to merge it in a separate pr!

**Pull request closed without merging**
