### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by Neetika146**
modified button

### CODE REVIEW

**Comment by yukseltron** [comment]
Hey @Neetika146 !

Could you explain a bit more about your button change? It's unclear why you want to change it.

**Comment by Neetika146** [comment]
It has more user friendly ui so it will create a better impact.

**Comment by Neetika146** [comment]
Plz accept my pull request 🙏🥲 I am just short of one request for
hacktoctoberfest

**Comment by yukseltron** [comment]
@Neetika146 
Unfortunately, I think changing the background-color goes against the monochrome theme of the site :/ 

If you make a more meaningful change, I'm sure that would get approved. I am not capable of approving.

**Comment by Neetika146** [comment]
Yeah! I would have done something better I understand that completely but
the deadline to contribute was till 31 oct only.🥲

**Comment by sakofchit** [comment]
Hi! 

Unfortunately I can't approve this since it doesn't match the monochrome criteria for this library.

**Pull request closed without merging**
